## Import the needed libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
from sklearn import preprocessing
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler #you can use minmax scaler too
from sklearn.model_selection import cross_val_score
#Import other necessary model libraries, for this example, using Logistic Regression

## Import the training data

In [2]:
train_data = pd.read_csv("../data/train_dataset.csv")

In [3]:
train_data.tail()

,primary_identifier,device_type,device_category,gender,district_name,age_group,network_stay,average_monthly_bill_amount,dusage_sum,dusage_min,...,vusage_offnet_max,vusage_offnet_min,vusage_offnet_days,vusage_offnet_avg,vusage_offnet_stddev,number_of_fixed_bb_accounts,number_of_iptv_accounts,add_on_tot_rental,add_on_count,next_month_plan
10495,1438655,4G,Smartphone,MALE,Kalutara,40-50,64,2088.13,479.0,0.346959,...,29.866667,0.0,7.0,14.571429,8.017054,0.0,0.0,NaN,NaN,PKG6
10496,7827264,4G,Smartphone,FEMALE,Colombo,<20,6,2053.50,23168.0,0.219985,...,25.366667,0.0,3.0,10.861111,5.151029,0.0,0.0,580.0,3.0,PKG1
10497,1433957,4G,Smartphone,FEMALE,Colombo,30-40,69,2827.33,4553.0,4.831711,...,0.000000,0.0,0.0,NaN,0.000000,0.0,1.0,NaN,NaN,PKG6
10498,8494507,4G,Smartphone,MALE,Kandy,60-70,233,645.43,2069.0,4.722031,...,18.650000,0.0,18.0,5.887963,4.956822,0.0,1.0,NaN,NaN,PKG1
10499,3569439,3G,Smartphone,MALE,Puttalam,40-50,33,498.20,536.0,0.003048,...,4.366667,0.0,7.0,2.228571,1.096541,0.0,0.0,NaN,NaN,PKG1

## Encoding Labels

In [4]:
train_data['next_month_plan'] = train_data['next_month_plan'].astype('category')

In [5]:
train_data['next_month_plan'].unique()

['PKG2', 'PKG1', 'PKG6', 'PKG4', 'PKG5', 'PKG3', 'PKG8', 'PKG7']
Categories (8, object): ['PKG2', 'PKG1', 'PKG6', 'PKG4', 'PKG5', 'PKG3', 'PKG8', 'PKG7']

In [6]:
labels_x = ['PKG0','PKG1', 'PKG2', 'PKG3', 'PKG4', 'PKG5', 'PKG6', 'PKG7', 'PKG8']

In [7]:
le = preprocessing.LabelEncoder()

In [8]:
le.fit(labels_x)

LabelEncoder()

In [9]:
le.classes_

array(['PKG0', 'PKG1', 'PKG2', 'PKG3', 'PKG4', 'PKG5', 'PKG6', 'PKG7',
       'PKG8'], dtype='<U4')

In [10]:
train_data['encoded_class_labels'] = le.transform(train_data['next_month_plan'])

In [11]:
train_data.head(20)

,primary_identifier,device_type,device_category,gender,district_name,age_group,network_stay,average_monthly_bill_amount,dusage_sum,dusage_min,...,vusage_offnet_min,vusage_offnet_days,vusage_offnet_avg,vusage_offnet_stddev,number_of_fixed_bb_accounts,number_of_iptv_accounts,add_on_tot_rental,add_on_count,next_month_plan,encoded_class_labels
0,6875768,4G,Smartphone,MALE,Kegalle,40-50,219,761.62,6317.0,2.773958,...,0.0,27.0,25.099383,34.759221,0.0,1.0,NaN,NaN,PKG2,2
1,6406277,4G,Smartphone,MALE,Galle,40-50,36,2482.52,28365.0,3.079438,...,0.0,15.0,5.071111,6.779644,0.0,0.0,600.0,2.0,PKG1,1
2,3563570,4G,Smartphone,MALE,Kandy,30-40,186,1565.55,18581.0,48.193713,...,0.0,0.0,NaN,0.000000,0.0,0.0,0.0,1.0,PKG6,6
3,1853666,4G,Smartphone,FEMALE,Colombo,40-50,24,2397.49,91071.0,22.437842,...,0.0,0.0,NaN,0.000000,0.0,0.0,1110.0,2.0,PKG4,4
4,2794331,4G,Smartphone,FEMALE,Kandy,50-60,37,2501.75,19736.0,53.302092,...,0.0,23.0,11.256522,16.224071,0.0,1.0,1350.0,2.0,PKG4,4
5,3619017,2G,Basic,MALE,Galle,40-50,30,495.54,0.0,0.001531,...,0.0,3.0,0.700000,0.233432,0.0,0.0,NaN,NaN,PKG1,1
6,7633257,4G,Smartphone,MALE,Kegalle,30-40,35,1977.19,14782.0,205.394300,...,0.0,0.0,NaN,0.000000,0.0,0.0,110.0,1.0,PKG5,5
7,5507217,4G,Smartphone,MALE,Gampaha,30-40,170,2925.00,3473.0,6.426329,...,0.0,0.0,NaN,0.000000,0.0,0.0,650.0,1.0,PKG5,5
8,7566055,4G,Smartphone,MALE,Kalutara,20-30,48,473.59,3870.0,0.000000,...,0.0,3.0,11.338889,4.661264,0.0,0.0,110.0,1.0,PKG2,2
9,7324903,4G,Smartphone,MALE,Colombo,20-30,81,1324.60,20876.0,3.450117,...,0.0,6.0,1.922222,1.310881,0.0,0.0,360.0,2.0,PKG2,2
10,4058040,4G,Smartphone,FEMALE,Kalutara,30-40,64,1612.70,11580.0,49.483975,...,0.0,7.0,3.959524,2.649690,0.0,0.0,740.0,2.0,PKG3,3
11,9835417,4G,Smartphone,FEMALE,Kurunegala,30-40,32,0.00,136.0,0.000000,...,0.0,2.0,1.283333,0.778115,0.0,0.0,110.0,1.0,PKG1,1
12,8104537,4G,Smartphone,MALE,Gampaha,30-40,26,1787.08,10043.0,40.711069,...,0.0,0.0,NaN,0.000000,0.0,0.0,NaN,NaN,PKG5,5
13,6937092,2G,Basic,MALE,Puttalam,40-50,178,496.34,0.0,0.000000,...,0.0,3.0,4.911111,2.560657,0.0,0.0,NaN,NaN,PKG1,1
14,3515441,3G,Smartphone,MALE,Galle,50-60,18,1528.66,1447.0,0.000000,...,0.0,5.0,4.273333,2.357698,0.0,0.0,NaN,NaN,PKG1,1
15,1254707,4G,Smartphone,FEMALE,Colombo,30-40,94,1826.41,3978.0,1.125170,...,0.0,11.0,4.310606,4.407215,0.0,0.0,350.0,1.0,PKG3,3
16,5038603,4G,Smartphone,FEMALE,Colombo,30-40,52,352.97,1862.0,2.095556,...,0.0,6.0,1.236111,0.657627,0.0,0.0,NaN,NaN,PKG2,2
17,3037770,2G,Feature phone,MALE,Kalutara,50-60,4,557.74,0.0,0.000000,...,0.0,22.0,2.231061,2.491781,0.0,0.0,NaN,NaN,PKG1,1
18,4669431,4G,Smartphone,FEMALE,Gampaha,20-30,57,4721.84,19508.0,205.565197,...,0.0,0.0,NaN,0.000000,0.0,0.0,2550.0,5.0,PKG3,3
19,8683145,4G,Smartphone,MALE,Galle,40-50,126,1165.14,325.0,0.000000,...,0.0,15.0,3.936667,3.213490,0.0,1.0,NaN,NaN,PKG2,2

## Handling Missing Values

In [12]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10500 entries, 0 to 10499
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   primary_identifier           10500 non-null  int64
 1   device_type                  10477 non-null  object
 2   device_category              10470 non-null  object
 3   gender                       10365 non-null  object
 4   district_name                10500 non-null  object
 5   age_group                    10365 non-null  object
 6   network_stay                 10500 non-null  int64
 7   average_monthly_bill_amount  10500 non-null  float64
 8   dusage_sum                   10500 non-null  float64
 9   dusage_min                   10500 non-null  float64
 10  dusage_max                   10500 non-null  float64
 11  dusage_avg                   9642 non-null   float64
 12  dusage_days                  10500 non-null  float64
 13  dusage_stddev                10500 non-null  float64
 14  vusage_onnet_sum             10500 non-null  float64
 15  vusage_onnet_max             10500 non-null  float64
 16  vusage_onnet_min             10500 non-null  float64
 17  vusage_onnet_days            10500 non-null  float64
 18  vusage_onnet_avg             1828 non-null   float64
 19  vusage_onnet_stddev          10500 non-null  float64
 20  vusage_offnet_sum            10500 non-null  float64
 21  vusage_offnet_max            10500 non-null  float64
 22  vusage_offnet_min            10500 non-null  float64
 23  vusage_offnet_days           10500 non-null  float64
 24  vusage_offnet_avg            7187 non-null   float64
 25  vusage_offnet_stddev         10500 non-null  float64
 26  number_of_fixed_bb_accounts  10500 non-null  float64
 27  number_of_iptv_accounts      10500 non-null  float64
 28  add_on_tot_rental            6667 non-null   float64
 29  add_on_count                 6667 non-null   float64
 30  next_month_plan              10500 non-null  category
 31  encoded_class_labels         10500 non-null  int64
dtypes: category(1), float64(23), int64(3), object(5)
memory usage: 2.5+ MB

In [13]:
train_data['device_category'].unique()

array(['Smartphone', 'Basic', 'Feature phone', 'Pluggable card', 'Tablet',
       nan, 'Modem'], dtype=object)

In [14]:
train_data['device_type'] = train_data['device_type'].fillna(value = 'Unknown')
train_data['device_category'] = train_data['device_category'].fillna(value = 'Unknown')
train_data['gender'] = train_data['gender'].fillna(value = 'Unknown')
train_data['age_group'] = train_data['age_group'].fillna(value = 'Unknown')

In [15]:
train_data = train_data.drop(columns = ['next_month_plan'])

In [16]:
train_data['dusage_avg'] = train_data['dusage_avg'].fillna(value = 0)
train_data['vusage_offnet_avg'] = train_data['vusage_offnet_avg'].fillna(value = 0)
train_data['add_on_tot_rental'] = train_data['add_on_tot_rental'].fillna(value = 0)
train_data['add_on_count'] = train_data['add_on_count'].fillna(value = 0)
train_data['vusage_onnet_avg'] = train_data['vusage_onnet_avg'].fillna(value = 0)

In [17]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10500 entries, 0 to 10499
Data columns (total 31 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   primary_identifier           10500 non-null  int64
 1   device_type                  10500 non-null  object
 2   device_category              10500 non-null  object
 3   gender                       10500 non-null  object
 4   district_name                10500 non-null  object
 5   age_group                    10500 non-null  object
 6   network_stay                 10500 non-null  int64
 7   average_monthly_bill_amount  10500 non-null  float64
 8   dusage_sum                   10500 non-null  float64
 9   dusage_min                   10500 non-null  float64
 10  dusage_max                   10500 non-null  float64
 11  dusage_avg                   10500 non-null  float64
 12  dusage_days                  10500 non-null  float64
 13  dusage_stddev                10500 non-null  float64
 14  vusage_onnet_sum             10500 non-null  float64
 15  vusage_onnet_max             10500 non-null  float64
 16  vusage_onnet_min             10500 non-null  float64
 17  vusage_onnet_days            10500 non-null  float64
 18  vusage_onnet_avg             10500 non-null  float64
 19  vusage_onnet_stddev          10500 non-null  float64
 20  vusage_offnet_sum            10500 non-null  float64
 21  vusage_offnet_max            10500 non-null  float64
 22  vusage_offnet_min            10500 non-null  float64
 23  vusage_offnet_days           10500 non-null  float64
 24  vusage_offnet_avg            10500 non-null  float64
 25  vusage_offnet_stddev         10500 non-null  float64
 26  number_of_fixed_bb_accounts  10500 non-null  float64
 27  number_of_iptv_accounts      10500 non-null  float64
 28  add_on_tot_rental            10500 non-null  float64
 29  add_on_count                 10500 non-null  float64
 30  encoded_class_labels         10500 non-null  int64
dtypes: float64(23), int64(3), object(5)
memory usage: 2.5+ MB

## Creating pre-processing pipeline

In [18]:
train_data.columns

Index(['primary_identifier', 'device_type', 'device_category', 'gender',
       'district_name', 'age_group', 'network_stay',
       'average_monthly_bill_amount', 'dusage_sum', 'dusage_min', 'dusage_max',
       'dusage_avg', 'dusage_days', 'dusage_stddev', 'vusage_onnet_sum',
       'vusage_onnet_max', 'vusage_onnet_min', 'vusage_onnet_days',
       'vusage_onnet_avg', 'vusage_onnet_stddev', 'vusage_offnet_sum',
       'vusage_offnet_max', 'vusage_offnet_min', 'vusage_offnet_days',
       'vusage_offnet_avg', 'vusage_offnet_stddev',
       'number_of_fixed_bb_accounts', 'number_of_iptv_accounts',
       'add_on_tot_rental', 'add_on_count', 'encoded_class_labels'],
      dtype='object')

In [19]:
data_cat_cols = ['device_type', 'device_category', 'gender', 'district_name', 'age_group']

In [20]:
data_quan_cols = ['network_stay','average_monthly_bill_amount', 'dusage_sum', 
                  'dusage_min', 'dusage_max','dusage_avg', 'dusage_days', 
                  'dusage_stddev', 'vusage_onnet_sum','vusage_onnet_max', 
                  'vusage_onnet_min', 'vusage_onnet_days','vusage_onnet_avg',
                  'vusage_onnet_stddev','vusage_offnet_sum', 'vusage_offnet_max','vusage_offnet_min', 
                  'vusage_offnet_days', 'vusage_offnet_avg','vusage_offnet_stddev', 
                  'number_of_fixed_bb_accounts','number_of_iptv_accounts', 
                  'add_on_tot_rental', 'add_on_count']

In [21]:
X = train_data.drop(columns=['encoded_class_labels', 'primary_identifier'])

In [22]:
y = train_data['encoded_class_labels']

In [23]:
X_train, X_test, Y_train, Y_test = train_test_split(X, y, random_state=10, test_size = 0.05, stratify = y)

In [24]:
X_train.head(20)

,device_type,device_category,gender,district_name,age_group,network_stay,average_monthly_bill_amount,dusage_sum,dusage_min,dusage_max,...,vusage_offnet_sum,vusage_offnet_max,vusage_offnet_min,vusage_offnet_days,vusage_offnet_avg,vusage_offnet_stddev,number_of_fixed_bb_accounts,number_of_iptv_accounts,add_on_tot_rental,add_on_count
6155,4G,Smartphone,MALE,Colombo,60-70,39,831.92,34164.0,425.700622,1789.252680,...,5.0,3.600000,0.0,5.0,1.103333,0.672225,1.0,2.0,360.0,2.0
2288,4G,Smartphone,MALE,Kandy,20-30,93,2677.35,11984.0,2.270360,1055.490074,...,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
9714,4G,Smartphone,MALE,Colombo,40-50,92,2627.77,19830.0,114.694360,1129.623393,...,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
7157,4G,Smartphone,MALE,Colombo,40-50,158,4795.76,8498.0,13.755560,725.783259,...,114.0,17.050000,0.0,22.0,5.197727,4.522210,0.0,0.0,360.0,2.0
738,4G,Smartphone,MALE,Colombo,50-60,51,3978.40,36917.0,660.364806,2735.215541,...,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,1500.0,1.0
490,4G,Smartphone,FEMALE,Colombo,40-50,133,2582.98,6820.0,16.479900,766.500066,...,330.0,66.483333,0.0,18.0,18.367593,18.339099,0.0,1.0,650.0,1.0
467,4G,Smartphone,MALE,Kalutara,40-50,9,906.76,7652.0,0.043341,958.006304,...,104.0,17.700000,0.0,27.0,3.873457,4.288491,0.0,0.0,110.0,2.0
6161,4G,Smartphone,MALE,Colombo,30-40,32,2148.93,10470.0,24.448140,1649.124297,...,53.0,21.683333,0.0,9.0,5.916667,4.704471,0.0,0.0,0.0,0.0
1343,4G,Smartphone,MALE,Gampaha,40-50,10,2759.05,15901.0,102.143398,1233.143407,...,45.0,8.533333,0.0,11.0,4.140909,2.426823,0.0,0.0,0.0,0.0
5792,4G,Smartphone,MALE,Colombo,50-60,198,1069.44,13193.0,52.539788,1733.798770,...,31.0,13.333333,0.0,8.0,3.879167,2.785113,1.0,0.0,600.0,2.0
9711,4G,Smartphone,FEMALE,Gampaha,40-50,106,2126.13,5165.0,0.000000,960.163307,...,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,40.0,1.0
8101,4G,Smartphone,FEMALE,Kalutara,40-50,5,989.94,10032.0,342.528443,1654.087762,...,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,520.0,3.0
2582,4G,Smartphone,FEMALE,Gampaha,40-50,10,829.50,13010.0,0.000000,1781.257216,...,9.0,8.050000,0.0,2.0,4.900000,1.493245,0.0,0.0,410.0,2.0
3711,4G,Smartphone,FEMALE,Colombo,20-30,53,1010.39,2585.0,2.542772,485.774677,...,81.0,11.833333,0.0,25.0,3.258667,3.088797,0.0,0.0,200.0,1.0
2789,2G,Feature phone,MALE,Badulla,40-50,185,745.14,0.0,0.000000,0.000000,...,44.0,6.066667,0.0,21.0,2.099206,1.724081,0.0,1.0,0.0,0.0
5569,4G,Smartphone,FEMALE,Gampaha,30-40,88,2090.50,4069.0,16.297462,477.574168,...,299.0,33.616667,0.0,24.0,12.493750,10.299765,0.0,0.0,0.0,1.0
3744,4G,Smartphone,FEMALE,Gampaha,30-40,5,1405.05,2094.0,2.217326,295.740664,...,161.0,54.500000,0.0,13.0,12.434615,12.956256,0.0,0.0,350.0,1.0
714,2G,Basic,MALE,Kalutara,30-40,20,1039.11,0.0,0.000000,0.000000,...,47.0,14.933333,0.0,20.0,2.356667,2.953237,0.0,1.0,0.0,0.0
7060,4G,Smartphone,MALE,Jaffna,30-40,203,3112.37,6446.0,0.000751,887.345405,...,5.0,3.450000,0.0,3.0,1.766667,0.775940,0.0,0.0,800.0,3.0
6213,4G,Smartphone,FEMALE,Puttalam,>70,9,473.19,0.0,0.000000,0.000000,...,22.0,10.733333,0.0,9.0,2.475926,2.614520,0.0,0.0,0.0,0.0

In [25]:
X_train['age_group'].unique()

array(['60-70', '20-30', '40-50', '50-60', '30-40', '>70', 'Unknown',
       '<20'], dtype=object)

In [26]:
X_train.shape

(9975, 29)

In [27]:
quan_pipeline = Pipeline([
    ('std_scaler', StandardScaler())
])

quan_transformed = quan_pipeline.fit_transform(X_train[data_quan_cols])

In [28]:
data_pipeline = ColumnTransformer([
    ('numerical', quan_pipeline, data_quan_cols),
    ('categorical', OneHotEncoder(handle_unknown = 'ignore'), data_cat_cols),
    
])

train_data_processed = data_pipeline.fit_transform(X_train)

In [29]:
train_data_processed[0]

array([-0.73587856, -0.84948216,  1.34223453,  2.0988014 ,  0.18501643,
        1.2518874 ,  0.53621625,  0.16788833, -0.18788699, -0.2600062 ,
        0.        , -0.28080456, -0.27565714, -0.24650206, -0.47954691,
       -0.5031088 , -0.06635089, -0.42126523, -0.4872795 , -0.53776094,
        4.00769298,  3.49200503,  0.0538823 ,  0.60012268,  0.        ,
        0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
        0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
        0.        ,  0.        ])

In [30]:
X_test.head()

,device_type,device_category,gender,district_name,age_group,network_stay,average_monthly_bill_amount,dusage_sum,dusage_min,dusage_max,...,vusage_offnet_sum,vusage_offnet_max,vusage_offnet_min,vusage_offnet_days,vusage_offnet_avg,vusage_offnet_stddev,number_of_fixed_bb_accounts,number_of_iptv_accounts,add_on_tot_rental,add_on_count
231,4G,Smartphone,FEMALE,Colombo,30-40,11,1716.27,12647.0,0.000000,1875.519728,...,13.0,10.366667,0.0,4.0,3.395833,1.946967,0.0,0.0,250.0,1.0
9966,4G,Smartphone,MALE,Ratnapura,20-30,9,985.32,1089.0,0.000000,267.741177,...,30.0,5.850000,0.0,11.0,2.775758,1.919775,0.0,0.0,0.0,0.0
486,4G,Smartphone,MALE,Gampaha,40-50,108,3518.42,22732.0,0.000000,1351.566897,...,113.0,44.533333,0.0,4.0,28.425000,10.514607,0.0,0.0,760.0,2.0
9686,4G,Smartphone,MALE,Colombo,30-40,34,2559.86,14666.0,96.475040,1160.861369,...,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
6310,4G,Smartphone,FEMALE,Trincomalee,30-40,24,1802.86,31567.0,521.592237,1672.417785,...,52.0,24.683333,0.0,12.0,4.397222,4.734033,0.0,0.0,450.0,2.0

In [31]:
X_train.columns

Index(['device_type', 'device_category', 'gender', 'district_name',
       'age_group', 'network_stay', 'average_monthly_bill_amount',
       'dusage_sum', 'dusage_min', 'dusage_max', 'dusage_avg', 'dusage_days',
       'dusage_stddev', 'vusage_onnet_sum', 'vusage_onnet_max',
       'vusage_onnet_min', 'vusage_onnet_days', 'vusage_onnet_avg',
       'vusage_onnet_stddev', 'vusage_offnet_sum', 'vusage_offnet_max',
       'vusage_offnet_min', 'vusage_offnet_days', 'vusage_offnet_avg',
       'vusage_offnet_stddev', 'number_of_fixed_bb_accounts',
       'number_of_iptv_accounts', 'add_on_tot_rental', 'add_on_count'],
      dtype='object')

In [32]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 525 entries, 231 to 229
Data columns (total 29 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   device_type                  525 non-null    object
 1   device_category              525 non-null    object
 2   gender                       525 non-null    object
 3   district_name                525 non-null    object
 4   age_group                    525 non-null    object
 5   network_stay                 525 non-null    int64
 6   average_monthly_bill_amount  525 non-null    float64
 7   dusage_sum                   525 non-null    float64
 8   dusage_min                   525 non-null    float64
 9   dusage_max                   525 non-null    float64
 10  dusage_avg                   525 non-null    float64
 11  dusage_days                  525 non-null    float64
 12  dusage_stddev                525 non-null    float64
 13  vusage_onnet_sum             525 non-null    float64
 14  vusage_onnet_max             525 non-null    float64
 15  vusage_onnet_min             525 non-null    float64
 16  vusage_onnet_days            525 non-null    float64
 17  vusage_onnet_avg             525 non-null    float64
 18  vusage_onnet_stddev          525 non-null    float64
 19  vusage_offnet_sum            525 non-null    float64
 20  vusage_offnet_max            525 non-null    float64
 21  vusage_offnet_min            525 non-null    float64
 22  vusage_offnet_days           525 non-null    float64
 23  vusage_offnet_avg            525 non-null    float64
 24  vusage_offnet_stddev         525 non-null    float64
 25  number_of_fixed_bb_accounts  525 non-null    float64
 26  number_of_iptv_accounts      525 non-null    float64
 27  add_on_tot_rental            525 non-null    float64
 28  add_on_count                 525 non-null    float64
dtypes: float64(23), int64(1), object(5)
memory usage: 123.0+ KB

In [33]:
test_data_processed = data_pipeline.transform(X_test)

In [34]:
test_data_processed

array([[-1.12547584, -0.24995533, -0.01257233, ...,  0.        ,
         0.        ,  0.        ],
       [-1.15330422, -0.74548779, -0.74031586, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.22420048,  0.97177507,  0.62242452, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-1.04199071, -1.09860764, -0.80680636, ...,  0.        ,
         0.        ,  0.        ],
       [-0.91676301, -0.31827705, -0.75807185, ...,  0.        ,
         1.        ,  0.        ],
       [-1.16721841, -0.92795926, -0.74037883, ...,  0.        ,
         0.        ,  0.        ]])

### Loading Submission data

In [35]:
submission_data = pd.read_csv("../data/test_dataset_new.csv")

In [36]:
submission_data.head()

,primary_identifier,device_type,device_category,gender,district_name,age_group,network_stay,average_monthly_bill_amount,dusage_sum,dusage_min,...,vusage_offnet_sum,vusage_offnet_max,vusage_offnet_min,vusage_offnet_days,vusage_offnet_avg,vusage_offnet_stddev,number_of_fixed_bb_accounts,number_of_iptv_accounts,add_on_tot_rental,add_on_count
0,2003793,4G,Smartphone,MALE,Colombo,40-50,4,689.42,148,0.000000,...,0,0.000000,0.0,0,NaN,0.000000,0,1,NaN,NaN
1,1776101,4G,Smartphone,MALE,Colombo,40-50,7,799.93,300,0.180222,...,107,16.266667,0.0,21,5.107143,4.924111,0,0,NaN,NaN
2,6945050,2G,Basic,MALE,Colombo,20-30,20,1538.45,8215,0.000000,...,108,90.000000,0.0,8,13.558333,16.397071,0,0,110.0,2.0
3,2472049,4G,Smartphone,FEMALE,Matara,40-50,10,995.75,11613,0.000000,...,0,0.416667,0.0,2,0.333333,0.087355,0,0,NaN,NaN
4,7197266,4G,Smartphone,MALE,Kandy,30-40,154,553.61,26505,28.515345,...,0,0.000000,0.0,0,NaN,0.000000,0,0,350.0,1.0

## Handling missing values in submission data

In [37]:
submission_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 30 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   primary_identifier           4500 non-null   int64
 1   device_type                  4487 non-null   object
 2   device_category              4484 non-null   object
 3   gender                       4445 non-null   object
 4   district_name                4500 non-null   object
 5   age_group                    4445 non-null   object
 6   network_stay                 4500 non-null   int64
 7   average_monthly_bill_amount  4500 non-null   float64
 8   dusage_sum                   4500 non-null   int64
 9   dusage_min                   4500 non-null   float64
 10  dusage_max                   4500 non-null   float64
 11  dusage_avg                   4136 non-null   float64
 12  dusage_days                  4500 non-null   int64
 13  dusage_stddev                4500 non-null   float64
 14  vusage_onnet_sum             4500 non-null   int64
 15  vusage_onnet_max             4500 non-null   float64
 16  vusage_onnet_min             4500 non-null   float64
 17  vusage_onnet_days            4500 non-null   int64
 18  vusage_onnet_avg             785 non-null    float64
 19  vusage_onnet_stddev          4500 non-null   float64
 20  vusage_offnet_sum            4500 non-null   int64
 21  vusage_offnet_max            4500 non-null   float64
 22  vusage_offnet_min            4500 non-null   float64
 23  vusage_offnet_days           4500 non-null   int64
 24  vusage_offnet_avg            3074 non-null   float64
 25  vusage_offnet_stddev         4500 non-null   float64
 26  number_of_fixed_bb_accounts  4500 non-null   int64
 27  number_of_iptv_accounts      4500 non-null   int64
 28  add_on_tot_rental            2788 non-null   float64
 29  add_on_count                 2788 non-null   float64
dtypes: float64(15), int64(10), object(5)
memory usage: 1.0+ MB

In [38]:
submission_data['device_category'].unique()

array(['Smartphone', 'Basic', 'Feature phone', 'Unknown', nan, 'Tablet',
       'Pluggable card', 'Modem'], dtype=object)

In [39]:
submission_data['device_type'] = submission_data['device_type'].fillna(value = 'Unknown')
submission_data['device_category'] = submission_data['device_category'].fillna(value = 'Unknown')
submission_data['gender'] = submission_data['gender'].fillna(value = 'Unknown')
submission_data['age_group'] = submission_data['age_group'].fillna(value = 'Unknown')

In [40]:
submission_data['dusage_avg'] = submission_data['dusage_avg'].fillna(value = 0)
submission_data['vusage_offnet_avg'] = submission_data['vusage_offnet_avg'].fillna(value = 0)
submission_data['add_on_tot_rental'] = submission_data['add_on_tot_rental'].fillna(value = 0)
submission_data['add_on_count'] = submission_data['add_on_count'].fillna(value = 0)
submission_data['vusage_onnet_avg'] = submission_data['vusage_onnet_avg'].fillna(value = 0)

In [41]:
submission_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 30 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   primary_identifier           4500 non-null   int64
 1   device_type                  4500 non-null   object
 2   device_category              4500 non-null   object
 3   gender                       4500 non-null   object
 4   district_name                4500 non-null   object
 5   age_group                    4500 non-null   object
 6   network_stay                 4500 non-null   int64
 7   average_monthly_bill_amount  4500 non-null   float64
 8   dusage_sum                   4500 non-null   int64
 9   dusage_min                   4500 non-null   float64
 10  dusage_max                   4500 non-null   float64
 11  dusage_avg                   4500 non-null   float64
 12  dusage_days                  4500 non-null   int64
 13  dusage_stddev                4500 non-null   float64
 14  vusage_onnet_sum             4500 non-null   int64
 15  vusage_onnet_max             4500 non-null   float64
 16  vusage_onnet_min             4500 non-null   float64
 17  vusage_onnet_days            4500 non-null   int64
 18  vusage_onnet_avg             4500 non-null   float64
 19  vusage_onnet_stddev          4500 non-null   float64
 20  vusage_offnet_sum            4500 non-null   int64
 21  vusage_offnet_max            4500 non-null   float64
 22  vusage_offnet_min            4500 non-null   float64
 23  vusage_offnet_days           4500 non-null   int64
 24  vusage_offnet_avg            4500 non-null   float64
 25  vusage_offnet_stddev         4500 non-null   float64
 26  number_of_fixed_bb_accounts  4500 non-null   int64
 27  number_of_iptv_accounts      4500 non-null   int64
 28  add_on_tot_rental            4500 non-null   float64
 29  add_on_count                 4500 non-null   float64
dtypes: float64(15), int64(10), object(5)
memory usage: 1.0+ MB

In [42]:
prim_id = submission_data['primary_identifier']

In [43]:
submission_data.shape

(4500, 30)

In [44]:
submission_X = submission_data.drop(columns=['primary_identifier'])

In [45]:
submission_X.shape

(4500, 29)

## Pre-processing the submission data

In [46]:
submission_data_processed = data_pipeline.transform(submission_X)

In [47]:
submission_data_processed[0].shape

(72,)

## Model Code